### ISSUE TITLE
SVG Icon Issues with Fill

### ISSUE THREAD

**Issue by shartte** [db-ui/base#265]
I am trying to make a React MUI component lib that contains all icons transpiled into React Components (which can be done at build-time, but is cumbersome).

I noticed that the original icons have been modified to include the following fill rules:
`CSS variables (replace fill="#282D37" by fill="#282D37" style="fill: currentColor;fill: var(--db-icon-color, currentColor)")`

Theses fill rules cause a problem with svgr:
```
[...] fill="#EC0016" style={{fill: "#EC0016", fill: "var(--db-icon-pulse-color, #EC0016)"}} 
```

Typescript will complain about "fill" being defined twice in the object literal.

I am not sure the definition even needs to be like that. The CSS fill always overwrites the fill color defined via attribute, and why is the fallback for browsers not supporting var needed? Do we really support IE11? :P
If so, we could also just write `fill="currentColor" style="fill: var(--db-icon-color, currentColor)"`

**Comment by mfranzke** [comment]
@shartte good catch, thanks !
