### ISSUE TITLE
DB Yellow 900: which color is correct?

### ISSUE THREAD

**Issue by pschaub** [db-ui/base#304]
In DB Marketing Portal the color of `DB Yellow 900` is `#F75F00`:
https://marketingportal.extranet.deutschebahn.com/marketingportal/Design-Anwendungen/DB-UX-Design-System/Design-fuer-Apps-Web/Farben

In DB UI the color of `DB Yellow 900` is `#f05000`:
https://db-ui.github.io/base/?p=colors-colors

Which one is correct?

**Comment by mfranzke** [comment]
@leape to me it looks like that the color within the technical implementation is wrong – I couldn't have found the color within Zeplin, but the Marketingportal is pretty clear to me. What do you think?

**Comment by pschaub** [comment]
So will this color be fixed in the current technical implementation in the next days/weeks/months (v2)?

**Comment by mfranzke** [comment]
> So will this color be fixed in the current technical implementation in the next days/weeks/months (v2)?

Minutes.

**Comment by mfranzke** [comment]
This has just been released with `@db-ui/base` version [v0.21.5](https://github.com/db-ui/base/releases/tag/v0.21.5)
