### ISSUE TITLE
Tailwind Tokens: Breakpoints are inconsistent with guidelines

### ISSUE THREAD

**Issue by pschaub** [db-ui/base#326]
Currently the breakpoints **640px**, 768px, 1024px and **1280px** are set as Tailwind tokens:
https://github.com/db-ui/base/blob/1b6bbf49a72a625837f208776c098834793bb0a3/tokens/tailwind/screens.json#L1-L8

The guidelines are currently showing breakpoints at **440px**, 768px, 1024px and **1440px**:
![image](https://github.com/db-ui/base/assets/11846736/c94e5d57-38b2-4177-8373-4bdb34a5a35f)
Source: https://marketingportal.extranet.deutschebahn.com/marketingportal/Design-Anwendungen/DB-UX-Design-System/Design-fuer-Apps-Web/Layout

For reference: the TailwindCSS defaults can be found here: https://github.com/tailwindlabs/tailwindcss/blob/master/stubs/config.full.js#L781-L787

**Comment by pschaub** [comment]
Would it be possible to reconsider these specifications in the DB UX design?
Especially the size 1440px I find a bit too high - the 1280px in Tailwind are probably more appropriate.

**Comment by mfranzke** [comment]
We've spoken about this and would like to align it with the Marketingportal specification for the moment to be consistent on that. Nevertheless I totally agree on your opinion and this will be covered in the next version (DB UX Design System Core) that we're currently working on quite heavily.
